
services:
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data: {}

networks:
  default:
    external: true
    name: scoobydoo